-define(MIN_LIMIT,10000000).
-define(MAX_LIMIT,1000000000).
-define(MAX_ORDER,100000000000000).
-define(MIN_ORDER,100).
-define(MIN_OFFSET,10).			%% low limit for step to next rank
-define(MAX_OFFSET,30).			%% up limit for step to prev rank
-define(SCORE_OFFSET,0).		%% must be less than ?MIN_ORDER && for example if it`s necessary begin score from 100 then need setting to 99
-define(TABLE_NAME,lfu).
-define(TIMEOUT_CLEAN,30000).
-define(TIMEOUT_COUNT,10000).

-ifdef(support).
    -define(SUPPORT,true).
    -define(SECONDARY,kit).
-else.
    -define(SUPPORT,false).
    -define(SECONDARY,any).
-endif.
